# -*- coding: utf-8 -*-
"""AppNotiDash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ke-tUSx7I4aw1UiSKTxBxaA0A9xlmcB6
"""

import streamlit as st
import pandas as pd
import altair as alt

def main():
    df = pd.read_csv('appnotidata.csv')

    # Ensure SEND_TIME is in datetime format
    df['SEND_TIME'] = pd.to_datetime(df['SEND_TIME'])

    st.title("App Notifications Analysis")


    # Mapping of original TAGS_INCLUDED values to more user-friendly names
    tags_mapping = {
        'SEND2 I:END_QUARTER  IO:OR EO:OR': 'End of Quarter',
        'SEND2 I:START_GAME  IO:OR EO:OR': 'Start of Game',
        'SEND2 I:END_GAME  IO:OR EO:OR': 'End of Game',
        'SEND2 I:NEWS,START_GAME,END_QUARTER,END_GAME,TEAM_NEWS,NEWS E: IO:OR EO:OR': 'Experience Rating'
    }

    # Apply the mapping to the TAGS_INCLUDED column for the dropdown
    df['TAG_LABEL'] = df['TAGS_INCLUDED'].map(tags_mapping)

    # Dropdown for TAG_LABEL
    tags = df['TAG_LABEL'].unique()
    selected_tag_label = st.selectbox("Select Notification Type", tags)

    # Filter data based on selected tag label
    filtered_df = df[df['TAG_LABEL'] == selected_tag_label]

    # Create the bar chart
    chart = alt.Chart(filtered_df).mark_bar().encode(
        x=alt.X('SEND_TIME:T', title='Send Time'),
        y=alt.Y('CLICKS:Q', title='Clicks'),
        tooltip=['SEND_TIME', 'CLICKS']
    ).properties(
        width=700,
        height=400,
        title=f'Clicks Over Time for {selected_tag_label}'
    ).interactive()

    # Display the chart
    st.altair_chart(chart)

# Run the main function
if __name__ == "__main__":
    main()
