# -*- coding: utf-8 -*-
"""AppNotiDash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ke-tUSx7I4aw1UiSKTxBxaA0A9xlmcB6
"""

import streamlit as st
import pandas as pd
import altair as alt

def main():
    # Load your dataset (replace 'your_dataset.csv' with your actual dataset path)
    df = pd.read_csv('your_dataset.csv')

    # Ensure SEND_TIME is in datetime format
    df['SEND_TIME'] = pd.to_datetime(df['SEND_TIME'])

    # Streamlit app title
    st.title("App Notifications Analysis")

    # Dropdown for TAGS_INCLUDED
    tags = df['TAGS_INCLUDED'].unique()
    selected_tag = st.selectbox("Select Notification Type", tags)

    # Filter data based on selected tag
    filtered_df = df[df['TAGS_INCLUDED'] == selected_tag]

    # Create the bar chart
    chart = alt.Chart(filtered_df).mark_bar().encode(
        x=alt.X('SEND_TIME:T', title='Send Time'),
        y=alt.Y('CLICKS:Q', title='Clicks'),
        tooltip=['SEND_TIME', 'CLICKS']
    ).properties(
        width=700,
        height=400,
        title=f'Clicks Over Time for {selected_tag}'
    ).interactive()

    # Display the chart
    st.altair_chart(chart)

# Run the main function
if __name__ == "__main__":
    main()